[tool.poetry]
name = "data-trading"
version = "0.1.0"
description = ""
authors = ["joonho <jh.lee@spira-t.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
